name: futbol_klublari_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^5.0.3
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  sqflite: ^1.3.2+2

flutter:
  uses-material-design: true
  assets:
    - assets/